import type {ImageSourcePropType} from 'react-native';

import type {RavenQuestQuizQuestion} from '../../src/shared/types';
import {ravenQuestShuffle} from '../../src/shared/lib/shuffle';

export const ravenQuestQuizTotal = 10;

const ravenQuestQuizImages: ImageSourcePropType[] = [
  require('../../assets/imgs/stories/greeceDelphi.png'),
  require('../../assets/imgs/stories/egyptFalcon.png'),
  require('../../assets/imgs/stories/indiaMoonRiver.png'),
  require('../../assets/imgs/stories/aztecsRedSky.png'),
  require('../../assets/imgs/stories/greeceShipwreck.png'),
  require('../../assets/imgs/stories/egyptObsidianGate.png'),
  require('../../assets/imgs/stories/indiaTigerTemple.png'),
  require('../../assets/imgs/stories/aztecsUndergroundCity.png'),
  require('../../assets/imgs/stories/greeceSilverHarp.png'),
  require('../../assets/imgs/stories/egyptMoonTomb.png'),
  require('../../assets/imgs/stories/indiaEmeraldPalace.png'),
  require('../../assets/imgs/stories/aztecsGoldenEclipse.png'),
];

const ravenQuestMakeQuestion = (
  ravenQuestId: string,
  ravenQuestImageIndex: number,
  ravenQuestQuestion: string,
  ravenQuestOptions: string[],
  ravenQuestCorrect: string,
): RavenQuestQuizQuestion => ({
  ravenQuestId,
  ravenQuestQuestion,
  ravenQuestOptions,
  ravenQuestCorrect,
  ravenQuestImage:
    ravenQuestQuizImages[ravenQuestImageIndex],
});

const ravenQuestAllQuizQuestions: RavenQuestQuizQuestion[] = [
  ravenQuestMakeQuestion(
    'delphi-1',
    0,
    'Which civilization is connected to the Temple Beneath Delphi?',
    ['Greece', 'Egypt', 'India', 'Aztecs'],
    'Greece',
  ),
  ravenQuestMakeQuestion(
    'delphi-2',
    0,
    'Which culture used the oracle temples from the story?',
    ['Greece', 'India', 'Egypt', 'Aztecs'],
    'Greece',
  ),
  ravenQuestMakeQuestion(
    'delphi-3',
    0,
    'Which civilization inspired the underground library beneath the mountain?',
    ['Greece', 'Aztecs', 'Egypt', 'India'],
    'Greece',
  ),
  ravenQuestMakeQuestion(
    'delphi-4',
    0,
    'Which culture is connected to the laurel crown artifact?',
    ['Greece', 'Egypt', 'India', 'Aztecs'],
    'Greece',
  ),
  ravenQuestMakeQuestion(
    'falcon-1',
    1,
    'Which civilization appears in Chamber of the Sun Falcon?',
    ['Egypt', 'Greece', 'India', 'Aztecs'],
    'Egypt',
  ),
  ravenQuestMakeQuestion(
    'falcon-2',
    1,
    'Which culture built chambers beneath desert sands?',
    ['Egypt', 'India', 'Greece', 'Aztecs'],
    'Egypt',
  ),
  ravenQuestMakeQuestion(
    'falcon-3',
    1,
    'Which civilization used falcon symbolism in the story?',
    ['Egypt', 'Aztecs', 'Greece', 'India'],
    'Egypt',
  ),
  ravenQuestMakeQuestion(
    'falcon-4',
    1,
    'Which culture inspired the royal burial chamber?',
    ['Egypt', 'Greece', 'India', 'Aztecs'],
    'Egypt',
  ),
  ravenQuestMakeQuestion(
    'moon-river-1',
    2,
    'Which civilization appears in Palace of the Moon River?',
    ['India', 'Greece', 'Egypt', 'Aztecs'],
    'India',
  ),
  ravenQuestMakeQuestion(
    'moon-river-2',
    2,
    'Which culture inspired the glowing jungle palace?',
    ['India', 'Egypt', 'Greece', 'Aztecs'],
    'India',
  ),
  ravenQuestMakeQuestion(
    'moon-river-3',
    2,
    'Which civilization is connected to sacred rivers and moon ceremonies?',
    ['India', 'Aztecs', 'Greece', 'Egypt'],
    'India',
  ),
  ravenQuestMakeQuestion(
    'moon-river-4',
    2,
    'Which culture inspired the submerged temple behind waterfalls?',
    ['India', 'Egypt', 'Greece', 'Aztecs'],
    'India',
  ),
  ravenQuestMakeQuestion(
    'red-sky-1',
    3,
    'Which civilization built the Pyramid of the Red Sky?',
    ['Aztecs', 'Greece', 'Egypt', 'India'],
    'Aztecs',
  ),
  ravenQuestMakeQuestion(
    'red-sky-2',
    3,
    'Which culture inspired the giant calendar stone?',
    ['Aztecs', 'India', 'Greece', 'Egypt'],
    'Aztecs',
  ),
  ravenQuestMakeQuestion(
    'red-sky-3',
    3,
    'Which civilization appears in the jungle pyramid story?',
    ['Aztecs', 'Egypt', 'Greece', 'India'],
    'Aztecs',
  ),
  ravenQuestMakeQuestion(
    'red-sky-4',
    3,
    'Which culture is connected to the crimson sky prophecy?',
    ['Aztecs', 'Greece', 'Egypt', 'India'],
    'Aztecs',
  ),
  ravenQuestMakeQuestion(
    'poseidon-1',
    4,
    'Which mythology inspired Shipwreck of Poseidon?',
    ['Greece', 'Egypt', 'India', 'Aztecs'],
    'Greece',
  ),
  ravenQuestMakeQuestion(
    'poseidon-2',
    4,
    'Which civilization is connected to Poseidon?',
    ['Greece', 'Aztecs', 'India', 'Egypt'],
    'Greece',
  ),
  ravenQuestMakeQuestion(
    'poseidon-3',
    4,
    'Which culture inspired the sea cave ruins?',
    ['Greece', 'Egypt', 'India', 'Aztecs'],
    'Greece',
  ),
  ravenQuestMakeQuestion(
    'poseidon-4',
    4,
    'Which civilization used trident symbolism in the story?',
    ['Greece', 'India', 'Egypt', 'Aztecs'],
    'Greece',
  ),
  ravenQuestMakeQuestion(
    'obsidian-1',
    5,
    'Which civilization appears in Obsidian Gate?',
    ['Egypt', 'Greece', 'India', 'Aztecs'],
    'Egypt',
  ),
  ravenQuestMakeQuestion(
    'obsidian-2',
    5,
    'Which culture inspired the buried desert city?',
    ['Egypt', 'India', 'Greece', 'Aztecs'],
    'Egypt',
  ),
  ravenQuestMakeQuestion(
    'obsidian-3',
    5,
    'Which civilization used giant stone tomb entrances in the story?',
    ['Egypt', 'Greece', 'India', 'Aztecs'],
    'Egypt',
  ),
  ravenQuestMakeQuestion(
    'obsidian-4',
    5,
    'Which culture inspired the underground oasis temples?',
    ['Egypt', 'Aztecs', 'Greece', 'India'],
    'Egypt',
  ),
  ravenQuestMakeQuestion(
    'tiger-1',
    6,
    'Which civilization inspired Tiger Temple of Jaipur?',
    ['India', 'Egypt', 'Greece', 'Aztecs'],
    'India',
  ),
  ravenQuestMakeQuestion(
    'tiger-2',
    6,
    'Which culture is connected to tiger guardian legends?',
    ['India', 'Greece', 'Egypt', 'Aztecs'],
    'India',
  ),
  ravenQuestMakeQuestion(
    'tiger-3',
    6,
    'Which civilization appears in the desert temple story?',
    ['India', 'Egypt', 'Greece', 'Aztecs'],
    'India',
  ),
  ravenQuestMakeQuestion(
    'tiger-4',
    6,
    'Which culture inspired the royal festival murals?',
    ['India', 'Greece', 'Egypt', 'Aztecs'],
    'India',
  ),
  ravenQuestMakeQuestion(
    'jungle-1',
    7,
    'Which civilization appears in City Beneath the Jungle?',
    ['Aztecs', 'Greece', 'Egypt', 'India'],
    'Aztecs',
  ),
  ravenQuestMakeQuestion(
    'jungle-2',
    7,
    'Which culture inspired the underground jungle city?',
    ['Aztecs', 'Egypt', 'Greece', 'India'],
    'Aztecs',
  ),
  ravenQuestMakeQuestion(
    'jungle-3',
    7,
    'Which civilization used giant ceremonial sun discs in the story?',
    ['Aztecs', 'Greece', 'India', 'Egypt'],
    'Aztecs',
  ),
  ravenQuestMakeQuestion(
    'jungle-4',
    7,
    'Which culture inspired the buried jungle arena?',
    ['Aztecs', 'Egypt', 'Greece', 'India'],
    'Aztecs',
  ),
  ravenQuestMakeQuestion(
    'harp-1',
    8,
    'Which mythology inspired Cave of the Silver Harp?',
    ['Greece', 'Egypt', 'India', 'Aztecs'],
    'Greece',
  ),
  ravenQuestMakeQuestion(
    'harp-2',
    8,
    'Which civilization appears in the island cave story?',
    ['Greece', 'Aztecs', 'India', 'Egypt'],
    'Greece',
  ),
  ravenQuestMakeQuestion(
    'harp-3',
    8,
    'Which culture inspired the underground musical chamber?',
    ['Greece', 'India', 'Egypt', 'Aztecs'],
    'Greece',
  ),
  ravenQuestMakeQuestion(
    'harp-4',
    8,
    'Which civilization is connected to the silver harp artifact?',
    ['Greece', 'Egypt', 'India', 'Aztecs'],
    'Greece',
  ),
  ravenQuestMakeQuestion(
    'alexandria-1',
    9,
    'Which civilization appears in Moon Tomb of Alexandria?',
    ['Egypt', 'Greece', 'India', 'Aztecs'],
    'Egypt',
  ),
  ravenQuestMakeQuestion(
    'alexandria-2',
    9,
    'Which culture inspired the moon observatory beneath the ruins?',
    ['Egypt', 'Greece', 'India', 'Aztecs'],
    'Egypt',
  ),
  ravenQuestMakeQuestion(
    'alexandria-3',
    9,
    'Which civilization used star and moon symbolism in the story?',
    ['Egypt', 'India', 'Greece', 'Aztecs'],
    'Egypt',
  ),
  ravenQuestMakeQuestion(
    'alexandria-4',
    9,
    'Which culture inspired the underground harbor tunnels?',
    ['Egypt', 'Greece', 'India', 'Aztecs'],
    'Egypt',
  ),
  ravenQuestMakeQuestion(
    'elephant-1',
    10,
    'Which civilization inspired Emerald Elephant Palace?',
    ['India', 'Greece', 'Egypt', 'Aztecs'],
    'India',
  ),
  ravenQuestMakeQuestion(
    'elephant-2',
    10,
    'Which culture is connected to giant elephant statues?',
    ['India', 'Egypt', 'Greece', 'Aztecs'],
    'India',
  ),
  ravenQuestMakeQuestion(
    'elephant-3',
    10,
    'Which civilization appears in the flooded palace story?',
    ['India', 'Aztecs', 'Egypt', 'Greece'],
    'India',
  ),
  ravenQuestMakeQuestion(
    'elephant-4',
    10,
    'Which culture inspired the buried jungle sanctuary?',
    ['India', 'Greece', 'Egypt', 'Aztecs'],
    'India',
  ),
  ravenQuestMakeQuestion(
    'eclipse-1',
    11,
    'Which civilization inspired Temple of the Golden Eclipse?',
    ['Aztecs', 'Greece', 'Egypt', 'India'],
    'Aztecs',
  ),
  ravenQuestMakeQuestion(
    'eclipse-2',
    11,
    'Which culture appears in the mountain eclipse temple story?',
    ['Aztecs', 'Egypt', 'Greece', 'India'],
    'Aztecs',
  ),
  ravenQuestMakeQuestion(
    'eclipse-3',
    11,
    'Which civilization used giant eclipse symbols in the story?',
    ['Aztecs', 'Greece', 'India', 'Egypt'],
    'Aztecs',
  ),
  ravenQuestMakeQuestion(
    'eclipse-4',
    11,
    'Which culture inspired the buried observatory chamber?',
    ['Aztecs', 'Egypt', 'Greece', 'India'],
    'Aztecs',
  ),
];

export const ravenQuestPickQuizQuestions = () =>
  ravenQuestShuffle(ravenQuestAllQuizQuestions).slice(
    0,
    ravenQuestQuizTotal,
  );
