import type {ImageSourcePropType} from 'react-native';

import type {TrialPrompt} from '../../ExplorerMytthofTypes';
import {seededReorder} from '../../ExplorerMytthofLoungeKit/ExplorerMytthofShuffle';

export const trialRoundCount = 10;

const trialVisuals: ImageSourcePropType[] = [
  require('../../../elements/images/stories/greeceDelphi.png'),
  require('../../../elements/images/stories/egyptFalcon.png'),
  require('../../../elements/images/stories/indiaMoonRiver.png'),
  require('../../../elements/images/stories/aztecsRedSky.png'),
  require('../../../elements/images/stories/greeceShipwreck.png'),
  require('../../../elements/images/stories/egyptObsidianGate.png'),
  require('../../../elements/images/stories/indiaTigerTemple.png'),
  require('../../../elements/images/stories/aztecsUndergroundCity.png'),
  require('../../../elements/images/stories/greeceSilverHarp.png'),
  require('../../../elements/images/stories/egyptMoonTomb.png'),
  require('../../../elements/images/stories/indiaEmeraldPalace.png'),
  require('../../../elements/images/stories/aztecsGoldenEclipse.png'),
];

const assembleTrialPrompt = (
  entryKey: string,
  visualIndex: number,
  promptStem: string,
  responseChoices: string[],
  keyedResponse: string,
): TrialPrompt => ({
  entryKey,
  promptStem,
  responseChoices,
  keyedResponse,
  coverVisual:
    trialVisuals[visualIndex],
});

const trialPromptPool: TrialPrompt[] = [
  assembleTrialPrompt(
    'prompt-001',
    0,
    'Which civilization is connected to the Temple Beneath Delphi?',
    ['Greece', 'Egypt', 'India', 'Aztecs'],
    'Greece',
  ),
  assembleTrialPrompt(
    'prompt-002',
    0,
    'Which culture used the oracle temples from the story?',
    ['Greece', 'India', 'Egypt', 'Aztecs'],
    'Greece',
  ),
  assembleTrialPrompt(
    'prompt-003',
    0,
    'Which civilization inspired the underground library beneath the mountain?',
    ['Greece', 'Aztecs', 'Egypt', 'India'],
    'Greece',
  ),
  assembleTrialPrompt(
    'prompt-004',
    0,
    'Which culture is connected to the laurel crown artifact?',
    ['Greece', 'Egypt', 'India', 'Aztecs'],
    'Greece',
  ),
  assembleTrialPrompt(
    'prompt-005',
    1,
    'Which civilization appears in Chamber of the Sun Falcon?',
    ['Egypt', 'Greece', 'India', 'Aztecs'],
    'Egypt',
  ),
  assembleTrialPrompt(
    'prompt-006',
    1,
    'Which culture built chambers beneath desert sands?',
    ['Egypt', 'India', 'Greece', 'Aztecs'],
    'Egypt',
  ),
  assembleTrialPrompt(
    'prompt-007',
    1,
    'Which civilization used falcon symbolism in the story?',
    ['Egypt', 'Aztecs', 'Greece', 'India'],
    'Egypt',
  ),
  assembleTrialPrompt(
    'prompt-008',
    1,
    'Which culture inspired the royal burial chamber?',
    ['Egypt', 'Greece', 'India', 'Aztecs'],
    'Egypt',
  ),
  assembleTrialPrompt(
    'prompt-009',
    2,
    'Which civilization appears in Palace of the Moon River?',
    ['India', 'Greece', 'Egypt', 'Aztecs'],
    'India',
  ),
  assembleTrialPrompt(
    'prompt-010',
    2,
    'Which culture inspired the glowing jungle palace?',
    ['India', 'Egypt', 'Greece', 'Aztecs'],
    'India',
  ),
  assembleTrialPrompt(
    'prompt-011',
    2,
    'Which civilization is connected to sacred rivers and moon ceremonies?',
    ['India', 'Aztecs', 'Greece', 'Egypt'],
    'India',
  ),
  assembleTrialPrompt(
    'prompt-012',
    2,
    'Which culture inspired the submerged temple behind waterfalls?',
    ['India', 'Egypt', 'Greece', 'Aztecs'],
    'India',
  ),
  assembleTrialPrompt(
    'prompt-013',
    3,
    'Which civilization built the Pyramid of the Red Sky?',
    ['Aztecs', 'Greece', 'Egypt', 'India'],
    'Aztecs',
  ),
  assembleTrialPrompt(
    'prompt-014',
    3,
    'Which culture inspired the giant calendar stone?',
    ['Aztecs', 'India', 'Greece', 'Egypt'],
    'Aztecs',
  ),
  assembleTrialPrompt(
    'prompt-015',
    3,
    'Which civilization appears in the jungle pyramid story?',
    ['Aztecs', 'Egypt', 'Greece', 'India'],
    'Aztecs',
  ),
  assembleTrialPrompt(
    'prompt-016',
    3,
    'Which culture is connected to the crimson sky prophecy?',
    ['Aztecs', 'Greece', 'Egypt', 'India'],
    'Aztecs',
  ),
  assembleTrialPrompt(
    'prompt-017',
    4,
    'Which mythology inspired Shipwreck of Poseidon?',
    ['Greece', 'Egypt', 'India', 'Aztecs'],
    'Greece',
  ),
  assembleTrialPrompt(
    'prompt-018',
    4,
    'Which civilization is connected to Poseidon?',
    ['Greece', 'Aztecs', 'India', 'Egypt'],
    'Greece',
  ),
  assembleTrialPrompt(
    'prompt-019',
    4,
    'Which culture inspired the sea cave ruins?',
    ['Greece', 'Egypt', 'India', 'Aztecs'],
    'Greece',
  ),
  assembleTrialPrompt(
    'prompt-020',
    4,
    'Which civilization used trident symbolism in the story?',
    ['Greece', 'India', 'Egypt', 'Aztecs'],
    'Greece',
  ),
  assembleTrialPrompt(
    'prompt-021',
    5,
    'Which civilization appears in Obsidian Gate?',
    ['Egypt', 'Greece', 'India', 'Aztecs'],
    'Egypt',
  ),
  assembleTrialPrompt(
    'prompt-022',
    5,
    'Which culture inspired the buried desert city?',
    ['Egypt', 'India', 'Greece', 'Aztecs'],
    'Egypt',
  ),
  assembleTrialPrompt(
    'prompt-023',
    5,
    'Which civilization used giant stone tomb entrances in the story?',
    ['Egypt', 'Greece', 'India', 'Aztecs'],
    'Egypt',
  ),
  assembleTrialPrompt(
    'prompt-024',
    5,
    'Which culture inspired the underground oasis temples?',
    ['Egypt', 'Aztecs', 'Greece', 'India'],
    'Egypt',
  ),
  assembleTrialPrompt(
    'prompt-025',
    6,
    'Which civilization inspired Tiger Temple of Jaipur?',
    ['India', 'Egypt', 'Greece', 'Aztecs'],
    'India',
  ),
  assembleTrialPrompt(
    'prompt-026',
    6,
    'Which culture is connected to tiger guardian legends?',
    ['India', 'Greece', 'Egypt', 'Aztecs'],
    'India',
  ),
  assembleTrialPrompt(
    'prompt-027',
    6,
    'Which civilization appears in the desert temple story?',
    ['India', 'Egypt', 'Greece', 'Aztecs'],
    'India',
  ),
  assembleTrialPrompt(
    'prompt-028',
    6,
    'Which culture inspired the royal festival murals?',
    ['India', 'Greece', 'Egypt', 'Aztecs'],
    'India',
  ),
  assembleTrialPrompt(
    'prompt-029',
    7,
    'Which civilization appears in City Beneath the Jungle?',
    ['Aztecs', 'Greece', 'Egypt', 'India'],
    'Aztecs',
  ),
  assembleTrialPrompt(
    'prompt-030',
    7,
    'Which culture inspired the underground jungle city?',
    ['Aztecs', 'Egypt', 'Greece', 'India'],
    'Aztecs',
  ),
  assembleTrialPrompt(
    'prompt-031',
    7,
    'Which civilization used giant ceremonial sun discs in the story?',
    ['Aztecs', 'Greece', 'India', 'Egypt'],
    'Aztecs',
  ),
  assembleTrialPrompt(
    'prompt-032',
    7,
    'Which culture inspired the buried jungle arena?',
    ['Aztecs', 'Egypt', 'Greece', 'India'],
    'Aztecs',
  ),
  assembleTrialPrompt(
    'prompt-033',
    8,
    'Which mythology inspired Cave of the Silver Harp?',
    ['Greece', 'Egypt', 'India', 'Aztecs'],
    'Greece',
  ),
  assembleTrialPrompt(
    'prompt-034',
    8,
    'Which civilization appears in the island cave story?',
    ['Greece', 'Aztecs', 'India', 'Egypt'],
    'Greece',
  ),
  assembleTrialPrompt(
    'prompt-035',
    8,
    'Which culture inspired the underground musical chamber?',
    ['Greece', 'India', 'Egypt', 'Aztecs'],
    'Greece',
  ),
  assembleTrialPrompt(
    'prompt-036',
    8,
    'Which civilization is connected to the silver harp artifact?',
    ['Greece', 'Egypt', 'India', 'Aztecs'],
    'Greece',
  ),
  assembleTrialPrompt(
    'prompt-037',
    9,
    'Which civilization appears in Moon Tomb of Alexandria?',
    ['Egypt', 'Greece', 'India', 'Aztecs'],
    'Egypt',
  ),
  assembleTrialPrompt(
    'prompt-038',
    9,
    'Which culture inspired the moon observatory beneath the ruins?',
    ['Egypt', 'Greece', 'India', 'Aztecs'],
    'Egypt',
  ),
  assembleTrialPrompt(
    'prompt-039',
    9,
    'Which civilization used star and moon symbolism in the story?',
    ['Egypt', 'India', 'Greece', 'Aztecs'],
    'Egypt',
  ),
  assembleTrialPrompt(
    'prompt-040',
    9,
    'Which culture inspired the underground harbor tunnels?',
    ['Egypt', 'Greece', 'India', 'Aztecs'],
    'Egypt',
  ),
  assembleTrialPrompt(
    'prompt-041',
    10,
    'Which civilization inspired Emerald Elephant Palace?',
    ['India', 'Greece', 'Egypt', 'Aztecs'],
    'India',
  ),
  assembleTrialPrompt(
    'prompt-042',
    10,
    'Which culture is connected to giant elephant statues?',
    ['India', 'Egypt', 'Greece', 'Aztecs'],
    'India',
  ),
  assembleTrialPrompt(
    'prompt-043',
    10,
    'Which civilization appears in the flooded palace story?',
    ['India', 'Aztecs', 'Egypt', 'Greece'],
    'India',
  ),
  assembleTrialPrompt(
    'prompt-044',
    10,
    'Which culture inspired the buried jungle sanctuary?',
    ['India', 'Greece', 'Egypt', 'Aztecs'],
    'India',
  ),
  assembleTrialPrompt(
    'prompt-045',
    11,
    'Which civilization inspired Temple of the Golden Eclipse?',
    ['Aztecs', 'Greece', 'Egypt', 'India'],
    'Aztecs',
  ),
  assembleTrialPrompt(
    'prompt-046',
    11,
    'Which culture appears in the mountain eclipse temple story?',
    ['Aztecs', 'Egypt', 'Greece', 'India'],
    'Aztecs',
  ),
  assembleTrialPrompt(
    'prompt-047',
    11,
    'Which civilization used giant eclipse symbols in the story?',
    ['Aztecs', 'Greece', 'India', 'Egypt'],
    'Aztecs',
  ),
  assembleTrialPrompt(
    'prompt-048',
    11,
    'Which culture inspired the buried observatory chamber?',
    ['Aztecs', 'Egypt', 'Greece', 'India'],
    'Aztecs',
  ),
];

export const sampleTrialPrompts = () =>
  seededReorder(trialPromptPool).slice(
    0,
    trialRoundCount,
  );
